
site_name: Open Knowledge
theme:
  name: material
  features:
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.path
    - search.suggest
    - navigation.tabs

nav:
  - Home:
      - 'Home': index.md
      - 'References': references.md
  - Scenarios:
      - 'Scenarios': 'scenario/index.md'
      - 'Scenario 01': 'scenario/01.md'
      - 'Scenario 02': 'scenario/02.md'
      - 'Scenario 03': 'scenario/03.md'
      - 'Scenario 04': 'scenario/04.md'
      - 'Scenario 05': 'scenario/05.md'
      - 'Scenario 06': 'scenario/06.md'
      - 'Scenario 07': 'scenario/07.md'
      - 'Scenario 08': 'scenario/08.md'
      - 'Scenario 09': 'scenario/09.md'
      - 'Scenario 10': 'scenario/10.md'
      - 'Scenario 11': 'scenario/11.md'

  - Capture:
      - 'Capture - Integration': capture/01.md
      - 'Capture - Context': capture/02.md
      - 'Capture - Relevant': capture/03.md
  - Structure:
      - 'Structure - Article Node Type': structure/01/index.md
      - 'Structure - Issue Field': structure/02/index.md
      - 'Structure - Node Form': structure/03/index.md
      - 'Structure - Fields': structure/04/index.md
      - 'Structure - Node Types': structure/05/index.md
      - 'Structure - Field Access': structure/06/index.md
      - 'Structure - Basic Formatting': structure/07/index.md
      - 'Structure - Lists': structure/08/index.md
      - 'Structure - Hyperlinks': structure/09/index.md
      - 'Structure - Multilingual': structure/10/index.md
  - Reuse:
      - 'Reuse - Federated search': reuse/01.md
      - 'Reuse - DMZ': reuse/02.md
      - 'Reuse - Linking': reuse/03.md
      - 'Reuse - Linked Multiple': reuse/04.md
      - 'Reuse - Delete Link': reuse/05.md
      - 'Reuse - Link non KCS content': reuse/06.md
      - 'Reuse - Linked Revision': reuse/07.md
  - Improve:
      - 'Improve - Moderation Notes': improve/01.md
      - 'Improve 02': improve/02.md
      - 'Improve 03': improve/03.md
      - 'Improve - New Article Duplicate Check': improve/04.md
      - 'Improve - Merge Duplicates': improve/05.md
      - 'Improve - Edit Multiple Article Simultaneously': improve/06.md
  - Content Health:
      - 'Content Health - Meta Data': content health/01.md
      - 'Content Health - More Meta Data': content health/02.md
      - 'Content Health - Content Moderation': content health/03.md
      - 'Content Health - Restrict Search by Confidence': content health/04.md
      - 'Content Health 05': content health/05.md
      - 'Content Health 06': content health/06.md
      - 'Content Health - Auto Publish': content health/07.md
      - 'Content Health - Community Create/Edit Articles': content health/08.md
      - 'Content Health 09': content health/09.md
      - 'Content Health 10': content health/10.md
      - 'Content Health 11': content health/11.md
      - 'Content Health 12': content health/12.md
      - 'Content Health 13': content health/13.md
  - Process Integration:
      - 'Process Integration 01': process integration/01.md
      - 'Process Integration 02': process integration/02.md
      - 'Process Integration 03': process integration/03.md
      - 'Process Integration 04': process integration/04.md
      - 'Process Integration 05': process integration/05.md
      - 'Process Integration - Search Tuning': process integration/06.md
      - 'Process Integration - Indexing': process integration/07.md
      - 'Process Integration - SEO': process integration/08.md
      - 'Process Integration - Search Weights': process integration/09.md
      - 'Process Integration 10': process integration/10.md
      - 'Process Integration 11': process integration/11.md
  - Performance Assessment:
      - 'Performance Assessment 01': performance assessment/01.md
      - 'Performance Assessment - Citation Rate': performance assessment/02.md
      - 'Performance Assessment - Link Rate': performance assessment/03.md
      - 'Performance Assessment - Article State': performance assessment/04.md
      - 'Performance Assessment - Content Standard Checklist': performance assessment/05.md
      - 'Performance Assessment - Process Adherence Report': performance assessment/06.md
      - 'Performance Assessment - Incident Links': performance assessment/07.md
      - 'Performance Assessment 08': performance assessment/08.md
      - 'Performance Assessment 09': performance assessment/09.md
      - 'Performance Assessment 10': performance assessment/10.md
      - 'Performance Assessment 11': performance assessment/11.md
      - 'Performance Assessment 12': performance assessment/12.md
      - 'Performance Assessment 13': performance assessment/13.md
      - 'Performance Assessment 14': performance assessment/14.md
      - 'Performance Assessment 15': performance assessment/15.md
      - 'Performance Assessment 16': performance assessment/16.md
      - 'Performance Assessment 17': performance assessment/17.md
      - 'Performance Assessment 18': performance assessment/18.md
      - 'Performance Assessment 19': performance assessment/19.md
      - 'Performance Assessment 20': performance assessment/20.md
      - 'Performance Assessment 21': performance assessment/21.md
      - 'Performance Assessment 22': performance assessment/22.md
      - 'Performance Assessment 23': performance assessment/23.md
      - 'Performance Assessment 24': performance assessment/24.md
      - 'Performance Assessment 25': performance assessment/25.md
      - 'Performance Assessment 26': performance assessment/26.md

  - Tags: tags.md

  - 'Code Coverage': coverage/index.html
plugins:
  - search
  - tags:
      tags_file: tags.md

repo_url: https://git.drupalcode.org/project/open_knowledge
copyright: KCS® is a service mark of the Consortium for Service InnovationTM. Open Knowledge is not certified by the Consortium for Service Innovation.
extra:
  generator: false
  social:
    - icon: fontawesome/brands/gitlab
      link: https://git.drupalcode.org/project/open_knowledge